= {lab_name} : A Capture The Flag game.

This lab is a Capture The Flag (CTF) game.
A flag is an element of information related to security, such as a password, an IP address... that has to be discovered in a "mission".

This CTF has 4 missions, so there are 4 flags for you to discover.
The missions are in order.  You need to complete one mission and submit its flag to unlock the next one.

The briefing and first mission are described on the next page.
Successive missions are described directly by the {ctf_dashboard_url}[CTF dashboard] when they are unlocked.

== Winning the CTF

To win, you must collect a maximum number of points.
Each discovered flag brings you a certain amount of points:
 - Mission 1 : 80 points
 - Mission 2 : 100 points
 - Mission 3 : 100 points
 - Mission 4 : 240 points

But you also have to be fast, real fast !
Indeed, only the first one to discover a flag scores the maximum number of points for the corresponding mission.
Successive winners will collect a slightly less amount of points.

To help you go faster, each mission have some hints that you can have revealed.
Each hint, however, will cost a small number of points.

Good luck !

