= Mission Briefing

Welcome to the Security Task Force ; please have a seat !

A critical security alert was raised by the NS team (Network & Security team).
They claim that an application hosted on an OpenShift cluster has been compromised today, resulting in sensitive data being leaked out to an external server.
They also pointed our an unexpected login from a generic user account that is supposed to be the one used by the hacker.

The applications and operations team haven't been able to find any security issues nor in the applications nor in the secured pipelines.

We need you to help us find security issues on the platform.
In order to do so, we've set you up with an account that has similar permissions that the one identified by the NS team.

Your objective, as a DevSecOps expert, is to trace back the actions taken by the hacker and provide information to the security team who will then review and update our security best practices.


= First mission
Your first objective is to identify which application is leaking sensitive data and uncover the IP address of the hacker's external server.
Type that IP address on the {dashboard_url}[Dashboard] to unlock the second mission.


== Lab access

{openshift_url}[Openshift Console]

{acs_url}[Advanced Cluster Security for Kubernetes]

{gitops_url}[Openshift GitOps --Be careful to login with local provider and NOT Openshift SSO]

{gitea_customersapp_url}[Source Code of the customers application]

username: {username}

password: {password}  -- Be careful to use local logins when connecting to ArgoCD (Do not use Openshift SSO login as those users have no permission at all)


== Required utilities
(Challenge 2) https://www.base64decode.org/

(challenge 4) https://reqbin.com/

https://jsonformatter.org/json-pretty-print

== Documentation
{doc_openshift_api}[Openshift API Reference]



