= Mission Briefing

Welcome to the Security Task Force ; please have a seat !

A critical security alert was raised by the NS team (Network & Security team).
They claim that an application hosted on an OpenShift cluster has been compromised today, resulting in sensitive data being leaked out to an external server.
They also pointed our an unexpected login from a generic user account that is supposed to be the one used by the hacker.

The applications and operations team haven't been able to find any security issues nor in the applications nor in the secured pipelines.

We need you to help us find security issues on the platform.
In order to do so, we've set you up with an account that has similar permissions that the one identified by the NS team.

Your objective, as a DevSecOps expert, is to trace back the actions taken by the hacker and provide information to the security team who will then review and update our security best practices.

= Mission zero
Your first objective will be to identify which application is leaking sensitive data and uncover the network information of the hacker's infrastructure.
Type your response on the CTF Dashboard to unlock the second mission, and keep going until the final mission number 4.
Use the available tools to investigate. A tool is never used twice to solve a mission.

To begin your journey, login to the CTF dashboard and unlock your practice challenge.

====
https://ctfd-leaderboard.{openshift_cluster_ingress_domain}/challenges[CTF Dashboard^]

username: {user}

password: MTU4MDMx

====


= Lab access

====
Login to the Openshift Web Console with RH SSO

https://{console_url}[Openshift Console^]

username: {user}

password: {password} 


Login to ACS with Openshift SSO integration

https://central-stackrox.{openshift_cluster_ingress_domain}[Advanced Cluster Security for Kubernetes^]

username: {user}

password: {password} 

====

====
Login to Openshift Gitops with the local authentication provider (NOT with Openshift SSO integration)

https://openshift-gitops-server-openshift-gitops.{openshift_cluster_ingress_domain}[Openshift GitOps (ArgoCD)^]

username: {user}

password: {password} 

====

====

{gitea_console_url}/gitea/customers-app.git[Source Code of the customers application^]

====


== Required utilities
====
https://www.base64decode.org/[Base64 decoder (Challenge 2)^]

https://reqbin.com/[REST Client (Challenge 4)^] 
====

== Documentation
====
{doc_openshift_api}[Openshift API Reference^]
====

